POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "John Blogger",
    "title": "Test blog",
    "blogUrl": "johnsblog.com/testblog",
    "votes": 2,
    "user": "68386eb39df6020db2629c92"
}
